#ifndef TINYFSERR_H
#define TINYFSERR_H

#define INVALID_FD -1
#define READ_EOF -2
#define OFFSET_OUT_OF_BOUND -4
#define INVALID_FS_SIZE -8
#define INSUFFICIENT_SPACE -16
#define INVALID_FS_MOUNTING_FILE -32
#define ERR_DURING_UNMOUNTING -64
#define MOUNTING_MORE_THAN_ONE_FS -128

#endif
